<?php
// module/Album/view/album/album/add.phtml:

$title = 'Sign up';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('user', array('action' => 'register')));
$form->prepare();


echo $this->form()->openTag($form);
echo $this->formRow($form->get('userName'));
echo("<br>");
echo $this->formRow($form->get('userPassword'));
echo("<br>");
echo $this->formRow($form->get('confirmPassword'));
echo("<br>");
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();