<?php
        // module/Album/view/album/album/index.phtml:

        $title = $this->userName.'\'s albums';
        $this->headTitle($title);
        ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
<a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
</p>
<?php if(count($albums) == 0): echo('You don\'t have any albums yet');
else:?>
<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>


<?php

foreach ($albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album['title']);?></td>
    <td><?php echo $this->escapeHtml($album['artist']);?></td>
    <td>
        <a href="<?php echo $this->url('album',
             array('action'=>'edit', 'id' => $album['album_id']));?>">Edit</a>
        <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id' => $album['album_id']));?>">Delete</a>
        <a href="<?php echo $this->url('album',
            array('action'=>'tracklist', 'id' => $album['album_id']));?>">Track list</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
<?php
    if(isset($this->userName)):
?>
<?php endif; ?>
<?php endif; ?>
<br/>
<a href="<?php echo $this->url('user', array('action'=>'logout'));?>">Log out</a>